name: head
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'
  pull_request:
    branches:
      - '**'
    tags-ignore:
      - '*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: vars
        run: |
          echo ::set-output name=VERSION::${GITHUB_REF#refs/*/}@${GITHUB_SHA:0:7}
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 16
      - run: chmod +x gradlew
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
      - run: ./gradlew build
        env:
          MOD_VERSION: ${{ steps.vars.outputs.VERSION }}
      - uses: actions/upload-artifact@v2
        with:
          name: megane ${{ steps.vars.outputs.VERSION }}
          path: "build/*/libs/**.jar"
