name: release
on:
  push:
    tags: "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: vars
        run: |
          echo ::set-output name=VERSION::${GITHUB_REF#refs/*/}
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 16
      - run: chmod +x gradlew
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
      - run: ./gradlew build curseforge
        env:
          MOD_VERSION: ${{ steps.vars.outputs.VERSION }}
          CURSEFORGE_API: ${{ secrets.CURSEFORGE_API }}
      - uses: alexellis/upload-assets@0.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["build/*/libs/*[0-9.].jar"]'
      - uses : actions/upload-artifact@v2
        with :
          name : megane ${{ steps.vars.outputs.VERSION }}
          path : "build/*/libs/**.jar"
