name: release
on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'
  pull_request:
    branches:
      - '**'
    tags-ignore:
      - '*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: vars
        run: |
          echo ::set-output name=VERSION::build-${GITHUB_RUN_NUMBER}-git-${GITHUB_SHA:0:7}
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: 3.x
      - run: chmod +x megane
      - run: ./megane bundle
        env:
          MOD_VERSION: ${{ steps.vars.outputs.VERSION }}
      - uses : actions/upload-artifact@v2
        with :
          name : megane-${{ steps.vars.outputs.VERSION }}
          path : |
            output/*.jar
            input/META-INF/jars/*.jar