name: head
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'
  pull_request:
    branches:
      - '**'
    tags-ignore:
      - '*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: vars
        run: |
          echo "git_hash=${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
      - uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: ${{ github.repository != 'badasintended/megane' }}
      - run: chmod +x gradlew
      - run: ./gradlew build
        env:
          GIT_HASH: ${{ steps.vars.outputs.git_hash }}
      - uses: actions/upload-artifact@v4
        with:
          name: megane-${{ steps.vars.outputs.git_hash }}
          path: "./modules/**/build/libs/**.jar"
