name: head
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'
  pull_request:
    branches:
      - '**'
    tags-ignore:
      - '*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: vars
        run: |
          echo ::set-output name=git_hash::${GITHUB_SHA:0:7}
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - uses: gradle/gradle-build-action@v2
      - run: |
          chmod +x setup.sh
          ./setup.sh
      - run: |
          chmod +x ./gradlew
          ./gradlew build
        env:
          MOD_VERSION: ${{ steps.vars.outputs.git_hash }}
      - uses: actions/upload-artifact@v2
        with:
          name: megane-${{ steps.vars.outputs.git_hash }}
          path: "./**/build/libs/**.jar"
      - run: ./gradlew --stop
