name: release
on:
  push:
    tags: "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: vars
        run: |
          echo "version=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
      - uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: ${{ github.repository != 'badasintended/megane' }}
      - run: chmod +x gradlew
      - run: ./gradlew build publishMods --max-workers=4
        env:
          MOD_VERSION: ${{ steps.vars.outputs.version }}
          CURSEFORGE_API: ${{ secrets.CURSEFORGE_API }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: megane-${{ steps.vars.outputs.git_hash }}
          path: "./modules/**/build/libs/**.jar"
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.vars.outputs.version }}
          files: |
            ./modules/*/build/libs/*[0-9.].jar
            ./modules/*/*/build/libs/*[0-9.].jar
