name: release
on:
  push:
    tags:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: vars
        run: |
          echo ::set-output name=version::${GITHUB_REF#refs/*/}
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - uses: gradle/gradle-build-action@v2
      - run: |
          chmod +x setup.sh
          ./setup.sh
      - run: |
          chmod +x ./gradlew
          ./gradlew build publish curseforge modrinth
        env:
          MOD_VERSION: ${{ steps.vars.outputs.version }}
          GITLAB_TOKEN: ${{ secrets.GITLAB_MAVEN }}
          CURSEFORGE_API: ${{ secrets.CURSEFORGE_API }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
      - uses: actions/upload-artifact@v2
        with:
          name: megane-${{ steps.vars.outputs.version }}
          path: "./**/build/libs/**.jar"
      - uses: alexellis/upload-assets@0.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: |
            [
              "./build/libs/*[0-9.].jar",
              "./module-*/*/build/libs/*[0-9.].jar"
            ]
      - run: ./gradlew --stop
